/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: 999d08d10adbfb6dd9db4db6a2af8ad1)
interface __BaseEnv_CloudflareBindings {
	DB: D1Database;
	AUTH_RATE_LIMITER: RateLimit;
	DEFAULT_BREAK_MINUTES: string;
	DEFAULT_ONE_WAY_FARE: string;
	DEFAULT_TRIP_TYPE: string;
	OVERTIME_THRESHOLD_HOURS: string;
	SESSION_TTL_SECONDS: string;
	SETUP_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEFAULT_BREAK_MINUTES" | "DEFAULT_ONE_WAY_FARE" | "DEFAULT_TRIP_TYPE" | "OVERTIME_THRESHOLD_HOURS" | "SESSION_TTL_SECONDS" | "SETUP_TOKEN">> {}
}
